image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master
    - develop

build_script:
- cmd: >-
    powershell .\build.ps1 -Target Default -Verbosity diagnostic
    
artifacts:
- path: ./src/bin/Release/*.nupkg
  name: NuGet

deploy:
  provider: NuGet
  api_key:
    secure: 6I3eH/n0pwTwcvmXBT9iVkteIsW4MAJMuD9xy7EJuJbRYDHIDNOLrDvx+uFvETjK
  artifact: /.*\.nupkg/
  on:
    branch: master