image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master
    - develop

build_script:
- cmd: >-
    powershell .\build.ps1 -Target Default -Verbosity diagnostic
    
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet

deploy:
  provider: NuGet
  api_key:
    secure: 08VoeMu7J5NvW2Rhro9kRtzP53d6omvavlOgBaY32/WQt5ENeE3HKKCe1tbCDOUy
  artifact: /.*\.nupkg/
  on:
    branch: master