image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master
    - develop

build_script:
- cmd: >-
    powershell .\build.ps1 -Target Default -Verbosity diagnostic
    
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet